### ISSUE TITLE
申请新增 dev.packages.vyos.net 的镜像

### ISSUE THREAD

**Issue by ackema** [ustclug/mirrorrequest#329] opened 2022-07-07 03:14 UTC
### 项目介绍 / Project Introduction
vyos是一个完全开源的、基于Debian改造的网络操作系统，可以在各种硬件、虚机和云上运行，并为所有规模的网络提供功能。vyos有一套统一的命令行界面、以及可用于web页面的HTTP API。
vyos非常适合用于搭建软路由，在较多的可选方案中，因为统一命令行和HTTP API的存在，vyos具有较强的竞争力，使用的人也越来越多。

### 上游地址及镜像方式 / Upstream location & mirror method
本次申请，希望贵站能添加这个源 [dev.packages.vyos.net](http://dev.packages.vyos.net/) 的镜像，谢谢！

### 为什么希望添加该镜像 / Why do you want we to add this mirror
vyos的编译是基于Debian的Live build功能，需要访问上游源，主要的源包括：debian、debian security和vyos dev，其中debian和debian security已经在贵站有了镜像，我使用下来体验非常好！
但是vyos dev目前国内没有找到合适的镜像，导致编译到这个部分的时候，速度会非常慢、而且经常失败，希望贵站能添加这个镜像。

### 其他信息 / Extra information
无。

- 镜像容量（Mirror size）：不知道怎么统计。
- 该镜像需求是否曾在之前的 issue 中提出过：无。

**Comment by ksqsf** [comment] 2022-07-07 03:30
https://mirrors.ustc.edu.cn/vyos/

请问这个是否是你需要的镜像？还缺什么吗？

**Comment by taoky** [comment] 2022-07-07 07:49
Duplicate of https://github.com/ustclug/mirrorrequest/issues/284

另外虽然 status 页面显示同步错误，但应该大部分包都是正常的。

**Closed by taoky** 2022-07-07 07:49 UTC
Labels: new, needvote

**Comment by ackema** [comment] 2022-07-15 04:15
非常抱歉啊，前几天没注意看邮件。


我看了一下有点像，但是实际我试了一下，这个不是我要的镜像（或者更新不及时么？）：


----
E: Failed to fetch http://mirrors.ustc.edu.cn/debian/pool/main/t/tasksel/tasksel_3.68%2bdeb11u1_all.deb  Error reading from server - read (104: Connection reset by peer) [IP: 202.141.160.110 80]
E: Failed to fetch http://mirrors.ustc.edu.cn/debian/pool/main/p/python-cffi/python3-cffi-backend_1.14.5-1_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 202.141.160.110 80]
E: Failed to fetch http://mirrors.ustc.edu.cn/debian/pool/main/t/tiff/libtiff5_4.2.0-1%2bdeb11u1_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 202.141.160.110 80]
E: Failed to fetch https://mirrors.ustc.edu.cn/vyos/repositories/current/pool/main/l/linux-5.10.129-amd64-vyos/linux-image-5.10.129-amd64-vyos_5.10.129-1_amd64.deb  Error reading from server - read (5: Input/output error) [IP: 202.141.160.110 443]
E: Failed to fetch https://mirrors.ustc.edu.cn/vyos/repositories/current/pool/main/v/vici/python3-vici_5.7.2-1_all.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:dcc4a7059bcc2c1da1cddae50029272114875e050d68d8f2a6eae2dbb4738544
    - SHA1:bb667284bc6cea58b3d211c3d4b9acf62160f570 [weak]
    - MD5Sum:592b432b187315d61866599edd23542e [weak]
    - Filesize:7292 [weak]
   Hashes of received file:
    - SHA256:32e4c8c6638867ebae926078187f5f78ffac43da6bc2974fadf2b87a750cdafc
    - SHA1:007e4963b11d89d9f326a6130e28b112eeaa403d [weak]
    - MD5Sum:e45a05332b81fc9431d05a260931ee2a [weak]
    - Filesize:7292 [weak]
   Last modification reported: Wed, 24 Jun 2020 17:58:34 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...
make: *** [Makefile:32: iso] Error 1


















在 2022-07-07 11:31:10，"ksqsf" ***@***.***> 写道：

https://mirrors.ustc.edu.cn/vyos/

请问这个是否是你需要的镜像？还缺什么吗？

**Comment by ackema** [comment] 2022-07-15 04:16
抱歉啊，前几天没注意邮件。


我试了一下，会报错：




----
E: Failed to fetch http://mirrors.ustc.edu.cn/debian/pool/main/t/tasksel/tasksel_3.68%2bdeb11u1_all.deb  Error reading from server - read (104: Connection reset by peer) [IP: 202.141.160.110 80]
E: Failed to fetch http://mirrors.ustc.edu.cn/debian/pool/main/p/python-cffi/python3-cffi-backend_1.14.5-1_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 202.141.160.110 80]
E: Failed to fetch http://mirrors.ustc.edu.cn/debian/pool/main/t/tiff/libtiff5_4.2.0-1%2bdeb11u1_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 202.141.160.110 80]
E: Failed to fetch https://mirrors.ustc.edu.cn/vyos/repositories/current/pool/main/l/linux-5.10.129-amd64-vyos/linux-image-5.10.129-amd64-vyos_5.10.129-1_amd64.deb  Error reading from server - read (5: Input/output error) [IP: 202.141.160.110 443]
E: Failed to fetch https://mirrors.ustc.edu.cn/vyos/repositories/current/pool/main/v/vici/python3-vici_5.7.2-1_all.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:dcc4a7059bcc2c1da1cddae50029272114875e050d68d8f2a6eae2dbb4738544
    - SHA1:bb667284bc6cea58b3d211c3d4b9acf62160f570 [weak]
    - MD5Sum:592b432b187315d61866599edd23542e [weak]
    - Filesize:7292 [weak]
   Hashes of received file:
    - SHA256:32e4c8c6638867ebae926078187f5f78ffac43da6bc2974fadf2b87a750cdafc
    - SHA1:007e4963b11d89d9f326a6130e28b112eeaa403d [weak]
    - MD5Sum:e45a05332b81fc9431d05a260931ee2a [weak]
    - Filesize:7292 [weak]
   Last modification reported: Wed, 24 Jun 2020 17:58:34 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...
make: *** [Makefile:32: iso] Error 1




















在 2022-07-07 15:50:09，"taoky" ***@***.***> 写道：

Duplicate of #284

另外虽然 status 页面显示同步错误，但应该大部分包都是正常的。

**Comment by taoky** [comment] 2022-07-15 05:05
> Connection reset by peer

关于 Debian 源，从错误信息看，你到科大镜像站的网络存在问题导致连接被中断。

关于 vyos 源，由于 vyos 会在不更新版本号的情况下更新包，目前的更新脚本无法处理这个问题。建议在 APT 配置中加入官方源作为后备。
