### ISSUE TITLE
新增openmediavault镜像

### ISSUE THREAD

**Issue by Huaweidev** [ustclug/mirrorrequest#376] opened 2023-10-18 06:40 UTC
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

[OpenMediaVault，是一个开源的基于Debian Linux的下一代网络附加存储(NAS)解决方案。](https://baike.baidu.com/item/OpenMediaVault/5404831)

### 上游地址与镜像方法 (Upstream & mirroring method)

Packages
The package repository can be accessed via https://packages.openmediavault.org/public. The repository is signed with:

PGP key ID: 2EF35D13
Fingerprint: 0F6B CC17 C26B FADC 27F2  2100 7E7A 6C59 2EF3 5D13
PGP key ID: 716B980B
Fingerprint: D675 06C8 78E0 8A94 FD7E  0094 2486 3F0C 716B 980B

**Comment by ritaanthem** [comment] 2023-10-19 05:44
Duplicate of #23

**Closed** 2023-10-19 05:48 UTC
Labels: new
