### ISSUE TITLE
virtualbox CentOS 7.x Repo

### ISSUE THREAD

**Issue by qwfys** [ustclug/mirrorrequest#248] opened 2019-11-13 12:06 UTC
**Please help us add the Virualbox Centos 7.x repository**

* Upstream URL：

```shell
yum install -y yum-utils
yum-config-manager --add-repo https://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
```

* Introduction of the project

&emsp;&emsp;VirtualBox is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use.

&emsp;&emsp;More please see [here](https://www.virtualbox.org/wiki/Documentation)

* Why do you hope we add this mirror

&emsp;&emsp;The techniques and features that Oracle VM VirtualBox provides are useful in the following scenarios:

&emsp;&emsp;Running multiple operating systems simultaneously. Oracle VM VirtualBox enables you to run more than one OS at a time. This way, you can run software written for one OS on another, such as Windows software on Linux or a Mac, without having to reboot to use it. Since you can configure what kinds of virtual hardware should be presented to each such OS, you can install an old OS such as DOS or OS/2 even if your real computer's hardware is no longer supported by that OS.

&emsp;&emsp;Easier software installations. Software vendors can use virtual machines to ship entire software configurations. For example, installing a complete mail server solution on a real machine can be a tedious task. With Oracle VM VirtualBox, such a complex setup, often called an appliance, can be packed into a virtual machine. Installing and running a mail server becomes as easy as importing such an appliance into Oracle VM VirtualBox.

&emsp;&emsp;Testing and disaster recovery. Once installed, a virtual machine and its virtual hard disks can be considered a container that can be arbitrarily frozen, woken up, copied, backed up, and transported between hosts.

&emsp;&emsp;On top of that, with the use of another Oracle VM VirtualBox feature called snapshots, one can save a particular state of a virtual machine and revert back to that state, if necessary. This way, one can freely experiment with a computing environment. If something goes wrong, such as prolems after installing software or infecting the guest with a virus, you can easily switch back to a previous snapshot and avoid the need of frequent backups and restores.

&emsp;&emsp;Any number of snapshots can be created, allowing you to travel back and forward in virtual machine time. You can delete snapshots while a VM is running to reclaim disk space.

&emsp;&emsp;Infrastructure consolidation. Virtualization can significantly reduce hardware and electricity costs. Most of the time, computers today only use a fraction of their potential power and run with low average system loads. A lot of hardware resources as well as electricity is thereby wasted. So, instead of running many such physical computers that are only partially used, one can pack many virtual machines onto a few powerful hosts and balance the loads between them.

>https://www.virtualbox.org/manual/UserManual.html#virt-why-useful

**Comment by iBug** [comment] 2020-06-24 13:57
duplicate of #22

**Closed by iBug** 2020-06-24 13:57 UTC
